### ISSUE TITLE
Albert Bio Update

### ISSUE THREAD

**Issue by naher94** [DzgnIO/dzgn.io#129]

**Comment by atopdjian** [comment]
Albert (pronounced Colbert but replace the “Co” with an “A”) has a degree in Industrial Design from Carnegie Mellon University. During his time at CMU, Albert has been mentored as an Innovation Scholar in the Center for Innovation and Entrepreneurship, was a soft-goods designer for Lexicon Design in Pittsburgh, and worked with American Eagle Outfitters as a UX Designer. Other than his professional accomplishments, Albert loves to cook, bike, windsurf, and play jazz music on any instrument he can find.

**Comment by atopdjian** [comment]
DOONNNEEE. Please close (I cannot)

**Comment by naher94** [comment]
not feeling the Al-bear verbiage lol

**Comment by atopdjian** [comment]
(pronounced Al-bear) instead of (pronounced Colbert but replace the “Co” with an “A”)
