### ISSUE TITLE
:active bug on globe

### ISSUE THREAD

**Issue by atopdjian** [DzgnIO/dzgn.io#130]
![screen shot 2017-08-09 at 3 52 29 pm](https://user-images.githubusercontent.com/11083239/29141111-de60f306-7d1a-11e7-9886-f4eecb2e3a49.png)

**Comment by naher94** [comment]
Can't see to reproduce this bug

**Comment by naher94** [comment]
Closing with https://github.com/DzgnIO/dzgn.io/pull/166
