### ISSUE TITLE
Glitchy Shift to the Right on Windows

### ISSUE THREAD

**Issue by lukehottinger** [DzgnIO/dzgn.io#20]
When opening a modal on a Windows machine, the site's content shifts to the right.

**Comment by lukehottinger** [comment]
Shed more light on the issue:
http://foundation.zurb.com/forum/posts/21450-reveal-modal-positioning-and-background-issues

**Comment by eddymankim** [comment]
A more recent thread
http://foundation.zurb.com/forum/posts/38019-scrollbar-page-jump-on-reveal-open?sort=Oldest

**Comment by naher94** [comment]
Solved With removing Modal
